### ISSUE TITLE
certain Sass files not included in the styleguide

### ISSUE THREAD

**Issue by mae** [markcipolla/vivus#4]
We have a rather large-ish app and we have at least 4 main stylesheets, I noticed that our application.scss does not get included in the styleguide, how is that possible? I thought because vivus' application.css file was overriding it so I made a new sass file but it doesn't get included either.

Thanks!

**Comment by mark-cipolla** [comment]
Hi @mae,

I've been busy with a bunch of my other projects, so Vivus has fallen a bit into disrepair. I've got plans to hugely simplify the gem, allowing you to configure what SCSS files you want to show in the documentation, but unfortunately, I've just not had the time.

It's a little bit abandoned at the moment, though I hope to come back to it soon.

-Mark

**Comment by mae** [comment]
Hi @markcipolla,

No problem! I figured it out by adding application.scss to assets.rb :)

Thank you so much for this project! I hope I can help as this is such a nice project but alas, I'm not much of a backend person :(
